# ????????????
workshop.api.call:
  # ???API?????????????
  #  host: localhost
  host: localhost
  port: 8080


# Servlet????
server:
  # ?????(localhost?API?????????????????)
  port: 8081


# ???????
logging.level:
  org.thymeleaf.TemplateEngine.TIMER: trace

spring:
  thymeleaf:
    prefix=classpath:/templates/:
    cache: false
  devtools:
    restart:
      enabled: true

authentication:
  tempPasswordLength: 8
  passwordExpireDays: 180
  tempPasswordExpireDays: 1


# ?????SpringBoot???????????????????Actuator????
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown
  endpoint:
    shutdown:
      enabled: true